### ISSUE TITLE
Dixoncoles really really slow

### ISSUE THREAD

**Issue by augihol** [Torvaney/regista#29]
Hey,
I find it odd that your dixoncoles is really fast with the embedded premier league dataset, while a subset of my own data (same size as premier league 2010) is super super slow.  Any tips? :)

**Comment by Torvaney** [comment]
That's interesting - do you mind me asking what dataset you're using? Is it the same number of teams/games (and therefore the same number of parameters)?

**Comment by augihol** [comment]
Hei,
this is the test dataset that I tried with. I tried to subset it to 380 observations as your premier league dataset. 

I am using data from over two years,  could this be the problem?

**My test dataset**
```
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	520 obs. of  7 variables:
 $ date  : chr  "2019-08-09" "2019-08-10" "2019-08-10" "2019-08-10" ...
 $ home  : Factor w/ 445 levels "Aberdeen","Accrington",..: 243 433 66 77 118 429 403 234 283 260 ...
 $ away  : Factor w/ 445 levels "Aberdeen","Accrington",..: 289 259 365 372 147 73 31 438 28 98 ...
 $ hgoal : num  4 0 1 3 0 0 3 0 0 4 ...
 $ agoal : num  1 5 1 0 0 3 1 0 1 0 ...
 $ result: Factor w/ 3 levels "A","D","H": 3 1 2 3 2 1 3 2 1 3 ...
 $ hfa   : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
```

I was also wondering if there is a way for your model to predict outcome more definitely: 
- You already have percentages for H, D and A, but is it possible to predict an outcome such as "H", "A", "D"  as definite outcome , where it select one of this three?- and also a way to test accuracy for these predictions?

Thank you alot btw for sharing this package :)

Ps.
I see HFA is set as HFA TRUE on all of the matches. Is this a default setting, or something that the model calculates for you? :)

**Comment by Torvaney** [comment]
>  Factor w/ 445 levels

I think this is what's slowing it down - are you trying to estimate the strengths of all 445 teams at once?

I would suggest splitting things out into "connected" leagues (only estimating for teams that can play each other at one time). For example, estimating the Scottish leagues separately from the English leagues.

---

> I was also wondering if there is a way for your model to predict outcome more definitely

Yes! :)

The `predict` method has an argument `type`, which determines whether to get scorelines, outcomes, or goalscoring rates for each match: http://regista.statsandsnakeoil.com/reference/predict.dixoncoles.html

See here for a more worked through example: http://www.statsandsnakeoil.com/2018/07/15/what-a-diff-rence-xg-makes/

**Comment by Torvaney** [comment]
> I see HFA is set as HFA TRUE on all of the matches. Is this a default setting, or something that the model calculates for you? :)


I _think_ by default, the `dixoncoles` function does this for you. But you can be more flexible with `dixoncoles_ext` if you need to.

**Comment by augihol** [comment]
Hey thank you. The issue resolved now. The issue was that my factor contained levels for all teams from european leagues, so no wonder it went slow. Thank you for you help!

**Comment by Torvaney** [comment]
No problem!
