### ISSUE TITLE
Support for arbitrary weighting

### ISSUE THREAD

**Issue by Torvaney** [Torvaney/regista#3]
The original Dixon-Coles model comes with a time-discount hyperparameter to down-weight games that took place long ago, relative to recent games.

This should be added to the default `dixoncoles` model. Something like:

```
res <- dixoncoles(~hgoal, ~agoal, ~home, ~away, time_discount_function, premier_league_2010)
```

The generic `dixoncoles_ext` could take an additional argument to control the weighting of games. This would allow weighting not just to time, but also things like friendly matches or anything else. For instance:

```
fit <- dixoncoles_ext(hgoal ~ off(home) + def(away) + hfa + 0,
                      agoal ~ off(home) + def(home) + 0,
                      weight = ~ some_weighting(column_name)
                      data = games)
```

With the evaluated `weight` argument being used to weight the log-likelihoods in the estimation step (as in the original paper).

**Comment by Torvaney** [comment]
Support for arbitrary weighting added in 59eacb527782bf9b046fde8da55c53af23429c7e, helpful time-discount function (+ documentation for hyper parameter search) TBD.

EDIT: actually - going to move these to separate issues

**Comment by farzadhass** [comment]
i have version 3.5 R. this package cannot install when i devtools::install_github("jogall/soccermatics")
do not load install and has error.how do solve this problem.
